-- ═══════════════════════════════════════════════════════════════════════════════
-- Sprout — baseline schema
--
-- Flyway owns this schema. EF Core maps to it and never migrates it; EF's own
-- migrations are switched off in Sprout.Infrastructure.DependencyInjection.
--
-- db/ef-model-snapshot.sql holds the DDL EF believes in, pinned by the
-- EfModelSnapshotTests test. This file must stay compatible with it. Where the two
-- deliberately differ, the difference is called out inline; every such case is SQL
-- expressing a rule EF cannot state, never a disagreement about shape.
-- ═══════════════════════════════════════════════════════════════════════════════

-- gen_random_uuid lives in pgcrypto on older servers and in core from PG13.
-- Ids are generated by the application (UUID v7), so this is only a safety net
-- for rows inserted by hand.
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ── ASP.NET Identity ──────────────────────────────────────────────────────────
-- Standard Identity tables, snake_cased to match the model walker in
-- Sprout.Infrastructure.Persistence.SnakeCaseNaming. display_name, initials and
-- avatar_color are Sprout's additions, and drive the member avatar circles.

CREATE TABLE asp_net_roles (
    id                  uuid NOT NULL,
    name                varchar(256),
    normalized_name     varchar(256),
    concurrency_stamp   text,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE UNIQUE INDEX role_name_index ON asp_net_roles (normalized_name);

CREATE TABLE asp_net_users (
    id                      uuid NOT NULL,
    display_name            varchar(80) NOT NULL,
    initials                varchar(2) NOT NULL,
    avatar_color            varchar(9) NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    user_name               varchar(256),
    normalized_user_name    varchar(256),
    email                   varchar(256),
    normalized_email        varchar(256),
    email_confirmed         boolean NOT NULL DEFAULT false,
    password_hash           text,
    security_stamp          text,
    concurrency_stamp       text,
    phone_number            text,
    phone_number_confirmed  boolean NOT NULL DEFAULT false,
    two_factor_enabled      boolean NOT NULL DEFAULT false,
    lockout_end             timestamptz,
    lockout_enabled         boolean NOT NULL DEFAULT true,
    access_failed_count     integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE INDEX email_index ON asp_net_users (normalized_email);
CREATE UNIQUE INDEX user_name_index ON asp_net_users (normalized_user_name);

CREATE TABLE asp_net_role_claims (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    role_id     uuid NOT NULL,
    claim_type  text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id
        FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE
);

CREATE INDEX ix_asp_net_role_claims_role_id ON asp_net_role_claims (role_id);

CREATE TABLE asp_net_user_claims (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    user_id     uuid NOT NULL,
    claim_type  text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id
        FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_asp_net_user_claims_user_id ON asp_net_user_claims (user_id);

CREATE TABLE asp_net_user_logins (
    login_provider          text NOT NULL,
    provider_key            text NOT NULL,
    provider_display_name   text,
    user_id                 uuid NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id
        FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_asp_net_user_logins_user_id ON asp_net_user_logins (user_id);

CREATE TABLE asp_net_user_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id
        FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id
        FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_asp_net_user_roles_role_id ON asp_net_user_roles (role_id);

CREATE TABLE asp_net_user_tokens (
    user_id         uuid NOT NULL,
    login_provider  text NOT NULL,
    name            text NOT NULL,
    value           text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id
        FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);


-- ── Refresh tokens ────────────────────────────────────────────────────────────
-- Only the SHA-256 of a token is stored, so a leaked table cannot be replayed
-- against the API. Rotation records the successor, which makes token reuse
-- detectable after the fact.

CREATE TABLE refresh_tokens (
    id                      uuid NOT NULL,
    user_id                 uuid NOT NULL,
    token_hash              varchar(64) NOT NULL,
    expires_at              timestamptz NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    revoked_at              timestamptz,
    replaced_by_token_id    uuid,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_asp_net_users_user_id
        FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

-- Sweeping expired tokens is a scheduled job, not a query path, so it gets its
-- own partial index rather than widening the ones above.
CREATE INDEX ix_refresh_tokens_expiry_sweep
    ON refresh_tokens (expires_at)
    WHERE revoked_at IS NULL;


-- ── List types and their categories ───────────────────────────────────────────
-- A type owns an ordered set of categories. That order is the "By category" sort
-- for every list of the type, which is why position lives here and not on a list.

CREATE TABLE list_types (
    id          uuid NOT NULL,
    owner_id    uuid NOT NULL,
    name        varchar(80) NOT NULL,
    blurb       varchar(120),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_list_types PRIMARY KEY (id),
    CONSTRAINT fk_list_types_asp_net_users_owner_id
        FOREIGN KEY (owner_id) REFERENCES asp_net_users (id) ON DELETE CASCADE,
    CONSTRAINT ck_list_types_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE INDEX ix_list_types_owner_id ON list_types (owner_id);

-- EF declares this unique on (owner_id, name); SQL enforces it case-insensitively,
-- which is the rule the domain actually applies when it rejects a duplicate.
CREATE UNIQUE INDEX ix_list_types_owner_id_name ON list_types (owner_id, lower(name));

CREATE TABLE categories (
    id              uuid NOT NULL,
    list_type_id    uuid NOT NULL,
    name            varchar(60) NOT NULL,
    palette_index   integer NOT NULL,
    position        integer NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_categories_list_types_list_type_id
        FOREIGN KEY (list_type_id) REFERENCES list_types (id) ON DELETE CASCADE,
    -- Six colours in the Organic palette; the domain cycles the index with the
    -- category count, so anything outside 0-5 is a bug rather than a new colour.
    CONSTRAINT ck_categories_palette_index CHECK (palette_index BETWEEN 0 AND 5),
    CONSTRAINT ck_categories_position CHECK (position >= 0),
    CONSTRAINT ck_categories_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE INDEX ix_categories_list_type_id_position ON categories (list_type_id, position);

-- As above: case-insensitive in SQL, matching ListType.AddCategory's own check.
CREATE UNIQUE INDEX ix_categories_list_type_id_name ON categories (list_type_id, lower(name));


-- ── Lists, items and members ──────────────────────────────────────────────────

CREATE TABLE todo_lists (
    id              uuid NOT NULL,
    owner_id        uuid NOT NULL,
    name            varchar(120) NOT NULL,
    list_type_id    uuid NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_todo_lists PRIMARY KEY (id),
    CONSTRAINT fk_todo_lists_asp_net_users_owner_id
        FOREIGN KEY (owner_id) REFERENCES asp_net_users (id) ON DELETE CASCADE,
    -- RESTRICT, not CASCADE: deleting a type that lists still use is refused with
    -- a 409 rather than quietly taking the lists with it.
    CONSTRAINT fk_todo_lists_list_types_list_type_id
        FOREIGN KEY (list_type_id) REFERENCES list_types (id) ON DELETE RESTRICT,
    CONSTRAINT ck_todo_lists_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE INDEX ix_todo_lists_owner_id ON todo_lists (owner_id);
CREATE INDEX ix_todo_lists_list_type_id ON todo_lists (list_type_id);

CREATE TABLE todo_items (
    id              uuid NOT NULL,
    todo_list_id    uuid NOT NULL,
    text            varchar(500) NOT NULL,
    category_id     uuid NOT NULL,
    due_on          date,
    is_completed    boolean NOT NULL DEFAULT false,
    completed_at    timestamptz,
    completed_by    uuid,
    position        integer NOT NULL,
    created_by      uuid NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_todo_items PRIMARY KEY (id),
    CONSTRAINT fk_todo_items_todo_lists_todo_list_id
        FOREIGN KEY (todo_list_id) REFERENCES todo_lists (id) ON DELETE CASCADE,
    -- The domain reaches a category only through the list's type, so EF maps this
    -- as a plain column. The database still refuses an item pointing at nothing,
    -- and RESTRICT is what forces DeleteCategoryCommand to rehome items first.
    CONSTRAINT fk_todo_items_categories_category_id
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_todo_items_asp_net_users_created_by
        FOREIGN KEY (created_by) REFERENCES asp_net_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_todo_items_asp_net_users_completed_by
        FOREIGN KEY (completed_by) REFERENCES asp_net_users (id) ON DELETE SET NULL,
    CONSTRAINT ck_todo_items_text_not_blank CHECK (length(btrim(text)) > 0),
    -- completed_at and is_completed move together; a completed item always knows when.
    CONSTRAINT ck_todo_items_completed_consistency
        CHECK ((is_completed AND completed_at IS NOT NULL) OR (NOT is_completed AND completed_at IS NULL))
);

CREATE INDEX ix_todo_items_category_id ON todo_items (category_id);
CREATE INDEX ix_todo_items_todo_list_id_position ON todo_items (todo_list_id, position);
CREATE INDEX ix_todo_items_todo_list_id_is_completed ON todo_items (todo_list_id, is_completed);

CREATE TABLE list_members (
    id              uuid NOT NULL,
    todo_list_id    uuid NOT NULL,
    user_id         uuid,
    invited_email   varchar(256),
    role            integer NOT NULL,
    status          integer NOT NULL,
    sort            integer NOT NULL DEFAULT 0,
    show_completed  boolean NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_list_members PRIMARY KEY (id),
    CONSTRAINT fk_list_members_todo_lists_todo_list_id
        FOREIGN KEY (todo_list_id) REFERENCES todo_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_list_members_asp_net_users_user_id
        FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE,
    -- ListRole: 0 owner, 1 editor.
    CONSTRAINT ck_list_members_role CHECK (role IN (0, 1)),
    -- MembershipStatus: 0 invited, 1 active.
    CONSTRAINT ck_list_members_status CHECK (status IN (0, 1)),
    -- SortMode: 0 category, 1 my order, 2 due date, 3 alphabetical.
    CONSTRAINT ck_list_members_sort CHECK (sort BETWEEN 0 AND 3),
    -- A membership is either a live one with an account, or an invitation with an
    -- address. Neither state is allowed to be empty.
    CONSTRAINT ck_list_members_identified
        CHECK (user_id IS NOT NULL OR invited_email IS NOT NULL),
    CONSTRAINT ck_list_members_active_has_user
        CHECK (status <> 1 OR user_id IS NOT NULL)
);

CREATE INDEX ix_list_members_user_id ON list_members (user_id);

-- Partial unique indexes, which EF declares as plain non-unique ones: half these
-- rows have a null user_id and half a null invited_email, and a person or an
-- address should appear on a list exactly once.
CREATE UNIQUE INDEX ix_list_members_todo_list_id_user_id
    ON list_members (todo_list_id, user_id)
    WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX ix_list_members_todo_list_id_invited_email
    ON list_members (todo_list_id, lower(invited_email))
    WHERE invited_email IS NOT NULL;

-- One owner per list.
CREATE UNIQUE INDEX ix_list_members_one_owner
    ON list_members (todo_list_id)
    WHERE role = 0;
