CREATE TABLE asp_net_roles (
    id uuid NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);


CREATE TABLE asp_net_users (
    id uuid NOT NULL,
    display_name character varying(80) NOT NULL,
    initials character varying(2) NOT NULL,
    avatar_color character varying(9) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);


CREATE TABLE list_types (
    id uuid NOT NULL,
    owner_id uuid NOT NULL,
    name character varying(80) NOT NULL,
    blurb character varying(120),
    is_default boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_list_types PRIMARY KEY (id)
);


CREATE TABLE asp_net_role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE
);


CREATE TABLE asp_net_user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);


CREATE TABLE asp_net_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id uuid NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);


CREATE TABLE asp_net_user_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);


CREATE TABLE asp_net_user_tokens (
    user_id uuid NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);


CREATE TABLE refresh_tokens (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by_token_id uuid,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);


CREATE TABLE categories (
    id uuid NOT NULL,
    list_type_id uuid NOT NULL,
    name character varying(60) NOT NULL,
    palette_index integer NOT NULL,
    position integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_categories_list_types_list_type_id FOREIGN KEY (list_type_id) REFERENCES list_types (id) ON DELETE CASCADE
);


CREATE TABLE todo_lists (
    id uuid NOT NULL,
    owner_id uuid NOT NULL,
    name character varying(120) NOT NULL,
    list_type_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_todo_lists PRIMARY KEY (id),
    CONSTRAINT fk_todo_lists_list_types_list_type_id FOREIGN KEY (list_type_id) REFERENCES list_types (id) ON DELETE RESTRICT
);


CREATE TABLE list_members (
    id uuid NOT NULL,
    todo_list_id uuid NOT NULL,
    user_id uuid,
    invited_email character varying(256),
    role integer NOT NULL,
    status integer NOT NULL,
    sort integer NOT NULL,
    show_completed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_list_members PRIMARY KEY (id),
    CONSTRAINT fk_list_members_todo_lists_todo_list_id FOREIGN KEY (todo_list_id) REFERENCES todo_lists (id) ON DELETE CASCADE
);


CREATE TABLE todo_items (
    id uuid NOT NULL,
    todo_list_id uuid NOT NULL,
    text character varying(500) NOT NULL,
    category_id uuid,
    due_on date,
    quantity integer NOT NULL,
    is_completed boolean NOT NULL,
    completed_at timestamp with time zone,
    completed_by uuid,
    position integer NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_todo_items PRIMARY KEY (id),
    CONSTRAINT fk_todo_items_categories_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_todo_items_todo_lists_todo_list_id FOREIGN KEY (todo_list_id) REFERENCES todo_lists (id) ON DELETE CASCADE
);


CREATE INDEX ix_asp_net_role_claims_role_id ON asp_net_role_claims (role_id);


CREATE UNIQUE INDEX role_name_index ON asp_net_roles (normalized_name);


CREATE INDEX ix_asp_net_user_claims_user_id ON asp_net_user_claims (user_id);


CREATE INDEX ix_asp_net_user_logins_user_id ON asp_net_user_logins (user_id);


CREATE INDEX ix_asp_net_user_roles_role_id ON asp_net_user_roles (role_id);


CREATE INDEX email_index ON asp_net_users (normalized_email);


CREATE UNIQUE INDEX user_name_index ON asp_net_users (normalized_user_name);


CREATE UNIQUE INDEX ix_categories_list_type_id_name ON categories (list_type_id, name);


CREATE INDEX ix_categories_list_type_id_position ON categories (list_type_id, position);


CREATE INDEX ix_list_members_todo_list_id_invited_email ON list_members (todo_list_id, invited_email);


CREATE INDEX ix_list_members_todo_list_id_user_id ON list_members (todo_list_id, user_id);


CREATE INDEX ix_list_members_user_id ON list_members (user_id);


CREATE INDEX ix_list_types_owner_id ON list_types (owner_id);


CREATE UNIQUE INDEX ix_list_types_owner_id_name ON list_types (owner_id, name);


CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);


CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);


CREATE INDEX ix_todo_items_category_id ON todo_items (category_id);


CREATE INDEX ix_todo_items_todo_list_id_is_completed ON todo_items (todo_list_id, is_completed);


CREATE INDEX ix_todo_items_todo_list_id_position ON todo_items (todo_list_id, position);


CREATE INDEX ix_todo_lists_list_type_id ON todo_lists (list_type_id);


CREATE INDEX ix_todo_lists_owner_id ON todo_lists (owner_id);


